### ISSUE TITLE
Widen Julia compat entry for 1.6

### ISSUE THREAD

**Issue by FredericWantiez** [TuringLang/Libtask.jl#147]
Is there any reason why we need this to be `1.7` specifically ? Or can we target `1.6` as the LTS ?
https://github.com/TuringLang/Libtask.jl/blob/24b3d4b55d3d6f7687f7e40ccce4b27133183950/Project.toml#L17

**Comment by yebai** [comment]
The previous task-copying version of `Libtask` works well for Julia 1.6. The new tape-based mechanism for `Libtask` works with Julia IR, but there is a big compiler API refactoring in Julia 1.7. Thus, supporting pre-1.7 versions of Julia requires a lot of work, which is probably too much for us to maintain. See some details [here](https://github.com/TuringLang/Libtask.jl/pull/126#issuecomment-1048693294). I think it is fine to drop support for Julia 1.6 in newer versions of AdvancedPS as well, since it contains a lot of breaking changes already.

**Comment by FredericWantiez** [comment]
Thanks, I missed this part. That probably means `AdvancedPS` will only support 1.7 from here
