### ISSUE TITLE
Why not ccalling directly into libjulia instead of having `Libtask_jll`?

### ISSUE THREAD

**Issue by giordano** [TuringLang/Libtask.jl#85]
Maintaining a library like `Libtask_jll` which links to libjulia isn't super simple as you need to have libjulia_jll available in the first place and then build against all different variations.  Why don't you `ccall` directly into libjulia from Julia, instead of delegating the same work to an external library?  This would have the advantage of having `Libtask.jl` more readily available on all platforms and versions of Julia without depending on external libraries.

**Comment by KDr2** [comment]
In Libtask, we want to clone/copy an instance of `jl_task_t` which is an internal data structure of Julia. It's hard to do this because:
- libjulia doesn't provide an API to do this
- if we try to use `ccall` to call `memcpy` to do the work, we must know the size of `jl_task_t`, which varies between different versions of Julia. And even further we must set some of its (internal) fields to initial values and some other fields to the corresponding field values in the original `task_t`. All of these couldn't be done simply using `ccall`.

We are trying to devise a PR to the Julia Repo, but it is hard to make out a clean one. And we just figured out a way to make `Libtask_jll` not depend on the memory layout of `task_t` (which varies frequently): https://github.com/JuliaPackaging/Yggdrasil/pull/3176. With this PR, `Libtask_jll` will be stable. And if `task_t` changes again, what we should do is only to change some julia code in `Libtask` rather than c code in `Libtask_jll`.

**Comment by yebai** [comment]
Closed in favour of #93
